language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: dJ0OvMrAIzymQIr1J6peW3x2m/MATltyWR/vn7CPcUM5Ie5mUiD9bhu6wAd8CAXNQJvEXTUqiJve3pq8Gqm9gvcUjoU5kNhrTyu24MPz5PApPDrw9pKcvDrJtFCnqAm9jpZMdT/kYT3LqZSaeIaiyLGk7fb+1AlO/pdo0YbO+fIPwujKN9MBr4UVBQx2O/32THRRqlyeL6tbD5hLIY2ay2wMObEUQn1PWI096kIw30Auv6gpStxCoSv1gddxAX5b9OWxd15D/X3Iomy7IkfUdNJcf5pqpGXKmVKZLwHQJwiTo5v0omC03ZYGst3xOepZfWqfk4a/o5/wpCqUUwXJryFjymDJrq5+5HsXCiMBhedcUok6E9YD7KSEXshsTVD5Wxe11fGKzmclgknton5o5MSHPLK8PZu0FNBriZ6/tZPs3WNZCcGOLjf+chL58oZqNI5wfmGxMSHAqn4fZQQbd+g2WwIkoVTf7WNRwWJDLmhtxJdYKBV4ahMKCq/+Iscv+uQ5ZxP5k6eYkDKE6gR9c1TPI++F3k7MzxV49YIlccMnTs7L0Lr65PGrrt98cPWuh6IXuX9IZUFqie1hf/SHMPlokhoCnrcao/T9oiHuSFz3/vqOR3SVyrgJXJOJijEYFWNk1xpQKast3uV07AqWzx7zGMTw7K1slnXUYIq+1wk=
  app: react-bookmark-app
  on:
    repo: rrogerthat/react-capstone-bookmark-app
