language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Ed6n+7eDjTPbs9pI9N1Ouff53vWyLOUQG7aQyAHGHFkspk8J3pxLcOzHiFhsb4NcYC4fFoKD1JDFZpNZEvnTAHobw5NZ18HO7ErJL+XhhH8L7Mo/qH9oC0dXbD8segrODYrdIT4cFc+3yAyVfAws3oK7aTa0yOVGCgBf7ccMCnJ/xrdJmzp4ZNZJUvL02gbS5RGA6B7ofCVVE8YhOlNWIF2mIxulK4UTaUBZPoAWOOzRVQuhWvHjQnxfRvzq+xihLfLHnJ11IT9hbc4+SykLif7EAip5FuHwilbETZCJCW/v332SrXRvNMIR0U2T86Dnxfg2h/1jCGJs0Il+w4Xt2rMEy/rLsY/bi8bJy5XgJsKtHwtbykYcys9uX97B56ClBydryGgw/N95AxeH6xBHEUdeNpJspNeSbQ6jV3EbAVHJ+hAl5907CNvbtouHjvl8mIJEog+eLruWfCF3T8HGdnGDwlOpRZ9MIsHCmFVOWGk4NWC7SKEavS6RzfzMbg4pOHaEdOUfVGI6Y4WDTNO5CkgvSWmVMikpTWBT0QTLRx+HHrL8frlQj/L/Defe73RWOJC3eQRE8fu0WkTVwBA+TPrkI1nO56GWpLJwXp+cZ2HwXKFWJRhA7iaRLv69r4BL6fxK0tB/pzbSg400/DX6dGbvj+xjOLaj5WKvKYbouG4=
  app: react-bookmark-app
  on:
    repo: rrogerthat/react-capstone-bookmark-app